# Generated by Django 5.1.4 on 2024-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Image', 'Image')], max_length=10)),
            ],
        ),
    ]
