# Generated by Django 5.1.4 on 2024-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='type',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='size',
            field=models.IntegerField(),
        ),
    ]
